[build]
  functions = "netlify/functions"
  publish = "."
[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200
[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200
[[redirects]]
  from = "/api/validate"
  to = "/.netlify/functions/validate"
  status = 200
[[redirects]]
  from = "/api/checkout"
  to = "/.netlify/functions/checkout"
  status = 200
